### ISSUE TITLE
can't get StorageClass object by Get

### ISSUE THREAD

**Issue by helios741** [kubernetes-sigs/controller-runtime#1074]
I want to get a storageclass object from the cluster, use the following code：
```golang
// storagev1 "k8s.io/api/storage/v1"
func (r *reconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
	var sc storagev1.StorageClass
	
	dn := client.ObjectKey{Name: "testvmt", Namespace: "prophet-resource-cdh"}
	err := r.Get(context.Background(), dn, &sc)
	if err != nil {
		panic(err)
	}
	fmt.Println("---------------")
	fmt.Println(sc)
	fmt.Println("================")
	return ctrl.Result{}, nil
}
```

But I can get it with the following code:
```golang
func (r *reconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
	sc := &unstructured.Unstructured{}
	sc.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "storage.k8s.io",
		Kind:    "StorageClass",
		Version: "v1",
	})

	dn := client.ObjectKey{Name: "testvmt", Namespace: "prophet-resource-cdh"}
	err := r.Get(context.Background(), dn, sc)
	if err != nil {
		panic(err)
	}
	fmt.Println("---------------")
	fmt.Println(sc)
	fmt.Println("================")
	return ctrl.Result{}, nil
}
```
I want to find someone who implemented [reader.get](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/interfaces.go#L56) to find this problem. Can you tell me?I hope to find the problem and fix it.

**Comment by alvaroaleman** [comment]
@helios741 can you paste the error you are getting with the code in the first example?

**Comment by helios741** [comment]
@alvaroaleman will trigger panic as follows:
```shell
E0728 17:39:08.880185    9055 runtime.go:78] Observed a panic: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"StorageClass.storage.k8s.io \"testvmt\" not found", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc0000946c0), Code:404}} (StorageClass.storage.k8s.io "testvmt" not found)
goroutine 242 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1ffbd40, 0xc0000ea280)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1ffbd40, 0xc0000ea280)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/panic.go:679 +0x1b2
main.(*reconciler).Reconcile(0xc0003a51c0, 0xc0002a88e0, 0x14, 0xc000474364, 0x7, 0xc00022dca0, 0xc0000f2000, 0xc000438008, 0x23483c0)
	/Users/helios/Desktop/test/gobook/src/gitlab.4pd.io/pht3/oam-addon-sage/test/get_sc.go:36 +0x26a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00036c480, 0x2025300, 0xc000390000, 0x104d600)
	/Users/helios/Desktop/test/gobook/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00036c480, 0xc000479600)
	/Users/helios/Desktop/test/gobook/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00036c480)
	/Users/helios/Desktop/test/gobook/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000424170)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000424170, 0x233ac40, 0xc0004e4000, 0xc000010001, 0xc000362300)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000424170, 0x3b9aca00, 0x0, 0xc0003a6701, 0xc000362300)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.Until(0xc000424170, 0x3b9aca00, 0xc000362300)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/Users/helios/Desktop/test/gobook/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x328
panic: StorageClass.storage.k8s.io "testvmt" not found [recovered]
	panic: StorageClass.storage.k8s.io "testvmt" not found

goroutine 242 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1ffbd40, 0xc0000ea280)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/panic.go:679 +0x1b2
main.(*reconciler).Reconcile(0xc0003a51c0, 0xc0002a88e0, 0x14, 0xc000474364, 0x7, 0xc00022dca0, 0xc0000f2000, 0xc000438008, 0x23483c0)
	/Users/helios/Desktop/test/gobook/src/gitlab.4pd.io/pht3/oam-addon-sage/test/get_sc.go:36 +0x26a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00036c480, 0x2025300, 0xc000390000, 0x104d600)
	/Users/helios/Desktop/test/gobook/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00036c480, 0xc000479600)
	/Users/helios/Desktop/test/gobook/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00036c480)
	/Users/helios/Desktop/test/gobook/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000424170)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000424170, 0x233ac40, 0xc0004e4000, 0xc000010001, 0xc000362300)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000424170, 0x3b9aca00, 0x0, 0xc0003a6701, 0xc000362300)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133 +0xe2
k8s.io/apimachinery/pkg/util/wait.Until(0xc000424170, 0x3b9aca00, 0xc000362300)
	/Users/helios/Desktop/test/gobook/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/Users/helios/Desktop/test/gobook/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x328

Process finished with exit code 2

```

**Comment by alvaroaleman** [comment]
that error just means there is no storageclass with the given name. The underlying issue could be that your controller does not have permissions to watch storageclasses, using unstructured directly goes to the api, using proper types uses the cache. But this is speculation without seeing the whole code.

**Comment by cuisongliu** [comment]
```
dn := client.ObjectKey{Name: "testvmt", Namespace: ""}
```

delete namespace name , try it again? I think the sc resource is not has namespace.

**Comment by helios741** [comment]
@cuisongliu 
Thanks, it's ok.
but I think if the scope is global, you can ignore this parameter, it's not panic.
