### ISSUE TITLE
flag redefined: `ginkgo.seed` when implementing Webhook or Controller for the Core Type 

### ISSUE THREAD

**Issue by smitthakkar96** [kubernetes-sigs/controller-runtime#2033]
## Traceback

``` shell
❯ go test ./... -v
/var/folders/qx/2ky7rt7j7mz_jxmrpjvc40hndh1zjd/T/go-build918891453/b001/controllers.test flag redefined: ginkgo.seed
panic: /var/folders/qx/2ky7rt7j7mz_jxmrpjvc40hndh1zjd/T/go-build918891453/b001/controllers.test flag redefined: ginkgo.seed

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000124120, {0x250bc50, 0x3092b40}, {0xc0003920c0, 0xb}, {0x22f1895, 0x2a})
        /Users/s.thakkar/.goenv/versions/1.19.0/src/flag/flag.go:980 +0x2f9
flag.(*FlagSet).Int64Var(...)
        /Users/s.thakkar/.goenv/versions/1.19.0/src/flag/flag.go:767
github.com/onsi/ginkgo/v2/types.bindFlagSet({{0xc00064b500, 0x20, 0x21}, {0x21025a0, 0xc0001e6900}, {0x3064100, 0xd, 0xd}, {{0x0, 0x0}, ...}, ...}, ...)
        /Users/s.thakkar/go/1.19.0/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/flags.go:161 +0x709
github.com/onsi/ginkgo/v2/types.NewAttachedGinkgoFlagSet(...)
        /Users/s.thakkar/go/1.19.0/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/flags.go:113
github.com/onsi/ginkgo/v2/types.BuildTestSuiteFlagSet(0x3092b40, 0x3092260)
        /Users/s.thakkar/go/1.19.0/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/types/config.go:346 +0x5d8
github.com/onsi/ginkgo/v2.init.0()
        /Users/s.thakkar/go/1.19.0/pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/core_dsl.go:47 +0x66
FAIL    github.com/deliveryhero/pd-pre-flight-checks/controllers        0.439s
FAIL
```

## `PROJECT`

``` yaml
domain: deliveryhero
layout:
- go.kubebuilder.io/v3
projectName: pd-pre-flight-checks
repo: github.com/deliveryhero/pd-pre-flight-checks
resources:
- controller: true
  group: apps
  kind: Deployment
  path: k8s.io/api/apps/v1
  version: v1
  webhooks:
    validation: true
    webhookVersion: v1
version: "3"
```

## Structure

``` tree
├── Dockerfile
├── Makefile
├── PROJECT
├── README.md
├── api
│   └── v1
│       └── deployment_webhook.go
├── bin
│   ├── controller-gen
│   ├── k8s
│   │   └── 1.25.0-darwin-amd64
│   │       ├── etcd
│   │       ├── kube-apiserver
│   │       └── kubectl
│   └── setup-envtest
├── config
│   ├── certmanager
│   │   ├── certificate.yaml
│   │   ├── kustomization.yaml
│   │   └── kustomizeconfig.yaml
│   ├── default
│   │   ├── kustomization.yaml
│   │   ├── manager_auth_proxy_patch.yaml
│   │   ├── manager_config_patch.yaml
│   │   ├── manager_webhook_patch.yaml
│   │   └── webhookcainjection_patch.yaml
│   ├── manager
│   │   ├── kustomization.yaml
│   │   └── manager.yaml
│   ├── prometheus
│   │   ├── kustomization.yaml
│   │   └── monitor.yaml
│   ├── rbac
│   │   ├── auth_proxy_client_clusterrole.yaml
│   │   ├── auth_proxy_role.yaml
│   │   ├── auth_proxy_role_binding.yaml
│   │   ├── auth_proxy_service.yaml
│   │   ├── kustomization.yaml
│   │   ├── leader_election_role.yaml
│   │   ├── leader_election_role_binding.yaml
│   │   ├── role.yaml
│   │   ├── role_binding.yaml
│   │   └── service_account.yaml
│   └── webhook
│       ├── kustomization.yaml
│       ├── kustomizeconfig.yaml
│       ├── manifests.yaml
│       └── service.yaml
├── controllers
│   ├── deployment_controller.go
│   ├── deployment_controller_test.go
│   └── suite_test.go
├── cover.out
├── go.mod
├── go.sum
├── hack
│   └── boilerplate.go.txt
├── main.go
├── mocks
└── utils
    └── utils.go
```

I also tried bootstrapping the code again when but still the same error

**Comment by smitthakkar96** [comment]
Closing the issue wrong repository, sorry

**Comment by smitthakkar96** [comment]
Moved it here https://github.com/kubernetes-sigs/kubebuilder/discussions/3049
