### ISSUE TITLE
help wanted: integration test fails due to controller-runtime issue

### ISSUE THREAD

**Issue by Gekko0114** [kubernetes-sigs/controller-runtime#2263]
We are facing an issue with controller-runtime while creating integration-tests for [scheduler-plugin](https://github.com/kubernetes-sigs/scheduler-plugins). We would appreciate your comments on this.

In this [PR](https://github.com/kubernetes-sigs/scheduler-plugins/pull/549), we have created integration test using `mgr.Start(ctrl.SetupSignalHandler())`.  However, as [another test](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/test/integration/elasticquota_controller_test.go#L60-L76) also uses `mgr.Start(ctrl.SetupSignalHandler())`, we are encountering a panic [error](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_scheduler-plugins/549/pull-scheduler-plugins-integration-test-master/1642893318373249024).

> panic: close of closed channel
> goroutine 9857 [running]:
> sigs.k8s.io/controller-runtime/pkg/manager/signals.SetupSignalHandler()
> 	/home/prow/go/src/sigs.k8s.io/scheduler-plugins/vendor/sigs.k8s.io/controller-runtime/pkg/manager/signals/signal.go:31 +0x25
> sigs.k8s.io/scheduler-plugins/test/integration.TestPodGroupController.func1()
> 	/home/prow/go/src/sigs.k8s.io/scheduler-plugins/test/integration/podgroup_controller_test.go:78 +0x32
> created by sigs.k8s.io/scheduler-plugins/test/integration.TestPodGroupController
> 	/home/prow/go/src/sigs.k8s.io/scheduler-plugins/test/integration/podgroup_controller_test.go:77 +0x3dd
> FAIL	sigs.k8s.io/scheduler-plugins/test/integration	356.228s

I think this is because [`ctrl.SetupSignalHandler`](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/manager/signals/signal.go#L30) is being executed twice in a single `go test`.
Could you suggest how we can implement integration test in such cases?

**Comment by Gekko0114** [comment]
I've fixed my PR's issue, but I would appreciate any comments.
