### ISSUE TITLE
Panic in DeepCopyInto during client.List() due to data race

### ISSUE THREAD

**Issue by nathanperkins** [kubernetes-sigs/controller-runtime#2391]
One of our E2E tests failed with this stack trace:

```
2023-06-08T00:44:14Z    INFO    Observed a panic in reconciler: runtime error: index out of range [3] with length 0}
panic: runtime error: index out of range [3] with length 0 [recovered]
        panic: runtime error: index out of range [3] with length 0

goroutine 443 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x1bb1260, 0xc000d3d860})
        /usr/local/go/src/runtime/panic.go:884 +0x212
our-project/pkg/apis/networking/v1.(*NetworkGatewayGroupStatus).DeepCopyInto(0xc0008c5738, 0xc0008dd898)
        /workspace/pkg/apis/networking/v1/zz_generated.deepcopy.go:881 +0x43f
our-project/pkg/apis/networking/v1.(*NetworkGatewayGroup).DeepCopyInto(0xc0008c5600, 0xc0008dd760)
        /workspace/pkg/apis/networking/v1/zz_generated.deepcopy.go:780 +0x29e
our-project/pkg/apis/networking/v1.(*NetworkGatewayGroup).DeepCopy(...)
        /workspace/pkg/apis/networking/v1/zz_generated.deepcopy.go:789
our-project/pkg/apis/networking/v1.(*NetworkGatewayGroup).DeepCopyObject(0xc0008c5600?)
        /workspace/pkg/apis/networking/v1/zz_generated.deepcopy.go:795 +0x45
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*CacheReader).List(0xc000190400, {0x0?, 0xc000220ee0?}, {0x1fdb950?, 0xc000220ee0}, {0xc000693d90, 0x1, 0x1cdefb8?})
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go:169 +0x442
sigs.k8s.io/controller-runtime/pkg/cache.(*informerCache).List(0xc00012c060, {0x1fd3d78, 0xc000af7500}, {0x1fdb950, 0xc000220ee0}, {0xc000693d90, 0x1, 0x1})
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go:87 +0x131
sigs.k8s.io/controller-runtime/pkg/client.(*delegatingReader).List(0xc0008660c0, {0x1fd3d78, 0xc000af7500}, {0x1fdb950?, 0xc000220ee0?}, {0xc000693d90, 0x1, 0x1})
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go:142 +0x114
our-project/controllers.(*NetworkGatewayGroupReconciler).Reconcile(0xc0003ddf40, {0x1fd3d78, 0xc000af7500}, {{{0xc001133310?, 0xc000be9d08?}, {0xc001133320?, 0x40da67?}}})
        /workspace/controllers/ang_controller.go:108 +0x223
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1fd3d78?, {0x1fd3d78?, 0xc000af7500?}, {{{0xc001133310?, 0x19a1c20?}, {0xc001133320?, 0x10?}}})
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003043c0, {0x1fd3cd0, 0xc0008663c0}, {0x1ac97a0?, 0xc0003fe460?})
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:323 +0x3a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003043c0, {0x1fd3cd0, 0xc0008663c0})
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:231 +0x333
```

The code at `ang_controller.go:108` is fairly straightforward so it's unclear how this issue could have been on our side.

```
	var gateways v1.NetworkGatewayGroupList
	if err := r.List(ctx, &gateways, client.InNamespace(r.ClusterResourceNamespace)); err != nil {
		return ctrl.Result{}, fmt.Errorf("list gateways in namespace %q: %s", r.ClusterResourceNamespace, err)
	}
```

I searched for "panic" in controller-runtime issues but didn't see anything related to DeepCopy.

Using controller-runtime v0.14.7 and controller-tools v0.11.3.
```[tasklist]
### Tasks
```

**Comment by sbueringer** [comment]
Looks to me like the panic is in:
```go
our-project/pkg/apis/networking/v1.(*NetworkGatewayGroupStatus).DeepCopyInto(0xc0008c5738, 0xc0008dd898)
        /workspace/pkg/apis/networking/v1/zz_generated.deepcopy.go:881 +0x43f
```

This then seems to a problem in the generated deepcopy code / the deepcopy generator. So probably something in controller-tools if you use controller-gen to generate the deep copy code.

But I think without the type / deepcopy code it's impossible to further triage.

We should probably transfer the issue to controller-tools






CR is just re-panic'ing here: (just for completeness)
```
goroutine 443 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x1bb1260, 0xc000d3d860})
```

**Comment by nathanperkins** [comment]
This is the deepcopy code in question. It looks like we are experiencing a race condition between allocating the out conditions and running through the copy.

```
if in.Conditions != nil {
  in, out := &in.Conditions, &out.Conditions
  *out = make([]metav1.Condition, len(*in))
  for i := range *in {                 
    (*in)[i].DeepCopyInto(&(*out)[i]) // this line panics, probably because len(in) changed out-of-band
  }
}
```

We are experiencing this failure in a few test cases that modify the object. In one of our cases, the test is E2E so the test code and controller code are running in completely separate processes, and it is modifying the object spec, not the status and not the conditions.

It doesn't make sense to my why we would experience any race conditions. As far as I can tell, we haven't changed the MaxConcurrentReconciles from the default of 1 and we haven't kicked off any goroutines ourselves.

The only lead I have is that maybe the way we are listing and iterating over our objects in a way that can be interfered by changes in the cache.

```
var gateways v1.NetworkGatewayGroupList
if err := r.List(ctx, &gateways, client.InNamespace(r.ClusterResourceNamespace)); err != nil {
  return ctrl.Result{}, fmt.Errorf(...)
}
	
for _, gw := range gateways.Items {
  // Do some operations and call a func to update the conditions.
}
```

```
op, err := controllerutil.CreateOrPatch(ctx, rs.opts.Client, obj, func() error {
  return setStatusConditions(obj, conds)
})
if err != nil {
    return ctrl.Result{}, fmt.Errorf(...)
}
```

**Comment by vincepri** [comment]
Is DeepCopy disabled in the cache by chance?

**Comment by nathanperkins** [comment]
@vincepri, is that the UnsafeDisableDeepCopyByObject field? We haven't used that anywhere.

I assume that means that items should be deep copied by default so we shouldn't have any race conditions across List or Get calls?

I will double-check my code and see if we can reproduce it or catch anything with a race detector.

**Comment by nathanperkins** [comment]
Mystery solved :)

We ran a race detector in our test and found a race between that DeepCopy code and one of our controller predicates, which changes the object status conditions to nil so that they can be ignored.

Is it intended behavior for the predicates to work directly on the cached objects? It seems reasonable to me for performance, but it is a potential footgun.

We can fix our predicate. Not sure if this is actionable on controller-runtime side.

**Comment by sbueringer** [comment]
Tried to figure out how this works.

If I see correctly shared informers are storing the same object in the thread-stafe store and hand it over to handlers here: https://github.com/kubernetes/client-go/blob/master/tools/cache/controller.go#L449-L458

Then as far as I can tell there is no deepcopy anywhere until we call the predicates: https://github.com/kubernetes-sigs/controller-runtime/blob/13bba740ff6ea05a09b91e7b625fbcbdfea93d2f/pkg/internal/source/event_handler.go#L79-L83

(skipped a lot of steps in between)

I think at the very least we should document this behavior.


With a picture. I think the exact same object is stored in 5 and handed over in 6:

![client-go-controller-interaction (1)](https://github.com/kubernetes-sigs/controller-runtime/assets/4662360/7a6802c3-e054-4aef-a971-0173392c7476)
> https://github.com/kubernetes/sample-controller/blob/master/docs/images/client-go-controller-interaction.jpeg

**Comment by nathanperkins** [comment]
That makes sense and it matches up with the behavior we are seeing. We adjusted our predicates to DeepCopy the object status internally and the race detector was satisfied.

Documenting it seems like a good step. I assume this applies to MapFunc as well.

Does this mean that our predicates cannot trust the state of the object to be consistent through the entire function? Can they be changed by the cache?

**Comment by sbueringer** [comment]
They can be modified through the cache when UnsafeDisableDeepCopy is set. For this field we have a disclaimer though:
https://github.com/kubernetes-sigs/controller-runtime/blob/2c594459d151e487e8eebc284e858200778ccffd/pkg/cache/cache.go#L162-L168

I think in general the expectation is that nobody should modify an object in the case. And if folks know what they are doing they can disable the deecopy for get/list (but they still shouldn't modify the object)

**Comment by sbueringer** [comment]
> UnsafeDisableDeepCopy seems to be an adjustment for objects which are returned by Get and List.

Correct. But those objects are coming from the cache assuming the default client is used and for Get/List calls with normal API types (can be influenced by cache configuration). So one way objects in the cache could be modified is by setting `UnsafeDisableDeepCopy` Get/List'ing them and then modifying them without DeepCopy.

> I'm talking about the object which is passed to event predicates. It seems to be a reference to the object in the cache, which could be modified at any time? So could it change during the predicate function?

Good point. This seems like another place where those objects could be modified. I don't know enough about the shared informer implementation to assess if it guarantees that the objects are not modified if handlers are still be processed for an earlier version of the object.

**Comment by wenhuwang** [comment]
I encountered a similar problem, the controller had a concurrent map iteration and map write error in DeepCopyInto during client.Get(), the stack trace:
```
fatal error: concurrent map iteration and map write

goroutine 444 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).DeepCopyInto(0xc005bbfe20, 0xc005bf0320)
	/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/apis/meta/v1/zz_generated.deepcopy.go:684 +0x396
multicluster-ingress-manager/api/network/v1.(*IngressManager).DeepCopyInto(0xc005bbfe00, 0xc005bf0300)
	/workspace/multicluster-ingress-manager/api/network/v1/zz_generated.deepcopy.go:152 +0xc5
multicluster-ingress-manager/api/network/v1.(*IngressManager).DeepCopy(...)
	/workspace//multicluster-ingress-manager/api/network/v1/zz_generated.deepcopy.go:163
multicluster-ingress-manager/api/network/v1.(*IngressManager).DeepCopyObject(0xc005bbfe00?)
	/workspace//multicluster-ingress-manager/api/network/v1/zz_generated.deepcopy.go:169 +0x45
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*CacheReader).Get(0xc0004a89b0, {0xc005bdb320?, 0x1c9f4e0?}, {{0xc005bd50d0?, 0x1c902f5?}, {0xc005be8460?, 0x18173ff?}}, {0x1f72910, 0xc005bf0180}, {0x0, ...})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/cache/internal/cache_reader.go:88 +0x145
sigs.k8s.io/controller-runtime/pkg/cache.(*informerCache).Get(0xc000340040, {0x1f5ce58, 0xc005bdb320}, {{0xc005bd50d0?, 0x1?}, {0xc005be8460?, 0x2?}}, {0x1f72910?, 0xc005bf0180?}, {0x0, ...})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/cache/informer_cache.go:68 +0x205
sigs.k8s.io/controller-runtime/pkg/client.(*delegatingReader).Get(0xc000051f80, {0x1f5ce58, 0xc005bdb320}, {{0xc005bd50d0?, 0xc002f09ba8?}, {0xc005be8460?, 0x178?}}, {0x1f72910?, 0xc005bf0180?}, {0x0, ...})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/client/split.go:132 +0x1ab
multicluster-ingress-manager/internal/controller.(*IngressManagerStatusReconciler).Reconcile(0xc0005ca600, {0x1f5ce58, 0xc005bdb320}, {{{0xc005bd50d0?, 0x10?}, {0xc005be8460?, 0x40da67?}}})
	/workspace/multicluster-ingress-manager/internal/controller/ingressmanager_status_controller.go:80 +0x1c3
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1f5ce58?, {0x1f5ce58?, 0xc005bdb320?}, {{{0xc005bd50d0?, 0x1921b40?}, {0xc005be8460?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000788820, {0x1f5cdb0, 0xc000696340}, {0x1a9a800?, 0xc007596e60?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:323 +0x38f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000788820, {0x1f5cdb0, 0xc000696340})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:231 +0x333

goroutine 1 [select]:
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).Start(0xc0007e8c40, {0x1f5cdb0, 0xc000051200})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/manager/internal.go:509 +0x5f3
main.main()
	/workspace/multicluster-ingress-manager/cmd/main.go:167 +0xf71
```

Using controller-runtime v0.4.2， kubebuilder 3.9.1

my project have two controller to watch crd ingressmanager, after receiving the event, one controller will push ingress resources to multiple business clusters, and the other controller will listen to the ingress resource events of the corresponding business clusters. 
I am not sure whether the concurrent operation map error is caused by two controllers reconcile an ingressmanager resource at the same time.

**Comment by wenhuwang** [comment]
> @wenhuwang try using the go race detector. It discovered the responsible code for us pretty quickly.

go race detector: 
```
# go run -race cmd/main.go

I0831 11:00:37.448344   21882 main.go:166] starting manager
I0831 11:00:37.448902   21882 internal.go:369] "Starting server" path="/metrics" kind="metrics" addr="[::]:8080"
I0831 11:00:37.448911   21882 internal.go:369] "Starting server" kind="health probe" addr="[::]:8081"
I0831 11:00:37.449787   21882 controller.go:186] "Starting EventSource" controller="ingressmanager" controllerGroup="network.demo.io" controllerKind="IngressManager" source="kind source: *v1.IngressManager"
I0831 11:00:37.449794   21882 controller.go:186] "Starting EventSource" controller="ingressmanager" controllerGroup="network.demo.io" controllerKind="IngressManager" source="kind source: *v1.IngressManager"
I0831 11:00:37.449912   21882 controller.go:194] "Starting Controller" controller="ingressmanager" controllerGroup="network.demo.io" controllerKind="IngressManager"
I0831 11:00:37.449926   21882 controller.go:194] "Starting Controller" controller="ingressmanager" controllerGroup="network.demo.io" controllerKind="IngressManager"
I0831 11:00:37.552030   21882 controller.go:228] "Starting workers" controller="ingressmanager" controllerGroup="network.demo.io" controllerKind="IngressManager" worker count=5
I0831 11:00:37.552032   21882 controller.go:228] "Starting workers" controller="ingressmanager" controllerGroup="network.demo.io" controllerKind="IngressManager" worker count=5
==================
WARNING: DATA RACE
Read at 0x00c0003647a8 by goroutine 450:
  multicluster-ingress-manager/internal/controller.(*IngressManagerStatusReconciler).getEventHandler()
      /workspace/multicluster-ingress-manager/internal/controller/ingressmanager_status_controller.go:172 +0x270
  multicluster-ingress-manager/internal/controller.(*IngressManagerStatusReconciler).registerInformersAndStart()
      /workspace/multicluster-ingress-manager/internal/controller/ingressmanager_status_controller.go:126 +0x370
  multicluster-ingress-manager/internal/controller.(*IngressManagerStatusReconciler).buildResourceInformers()
      /workspace/multicluster-ingress-manager/internal/controller/ingressmanager_status_controller.go:108 +0xa0
  multicluster-ingress-manager/internal/controller.(*IngressManagerStatusReconciler).Reconcile()
      /workspace/multicluster-ingress-manager/internal/controller/ingressmanager_status_controller.go:103 +0x670
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:122 +0xe4
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:323 +0x3a0
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:274 +0x240
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:235 +0x98

Previous write at 0x00c0003647a8 by goroutine 454:
  multicluster-ingress-manager/internal/controller.(*IngressManagerStatusReconciler).getEventHandler()
      /workspace/multicluster-ingress-manager/internal/controller/ingressmanager_status_controller.go:173 +0x310
  multicluster-ingress-manager/internal/controller.(*IngressManagerStatusReconciler).registerInformersAndStart()
      /workspace/multicluster-ingress-manager/internal/controller/ingressmanager_status_controller.go:126 +0x370
  multicluster-ingress-manager/internal/controller.(*IngressManagerStatusReconciler).buildResourceInformers()
      /workspace/multicluster-ingress-manager/internal/controller/ingressmanager_status_controller.go:108 +0xa0
  multicluster-ingress-manager/internal/controller.(*IngressManagerStatusReconciler).Reconcile()
      /workspace/multicluster-ingress-manager/internal/controller/ingressmanager_status_controller.go:103 +0x670
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Contro  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:323 +0x3a0
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:274 +0x240
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:235 +0x98

Goroutine 450 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:231 +0x364
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:242 +0x254
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/manager/runnable_group.go:219 +0x158
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func2()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/manager/runnable_group.go:222 +0x44

Goroutine 454 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:231 +0x364
  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:242 +0x254
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/manager/runnable_group.go:219 +0x158
  sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func2()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/manager/runnable_group.go:222 +0x44
==================
```

**Comment by sbueringer** [comment]
Sorry but I think it doesn't make much sense to investigate what might happen with CR v0.4.2. Please upgrade to a new version

**Comment by Colvin-Y** [comment]
Hi @nathanperkins , is there any solution if we do need deepCopy from cache? I noticed that this issue has been marked as not planned, but I still encountered a similar problem in client-go 1.29.

**Comment by nathanperkins** [comment]
Our solution was to do the deep copy ourselves within the predicate function that modified the input.

**Comment by Colvin-Y** [comment]
> Our solution was to do the deep copy ourselves within the predicate function that modified the input.

@nathanperkins  Got it, thx
