### ISSUE TITLE
After upgrading controller-runtime from 0.10 to 0.15, InjectDecoder and admission.Decoder don't seem to be working!

### ISSUE THREAD

**Issue by zerunhu** [kubernetes-sigs/controller-runtime#2504]
Problematic controller-runtime version: 0.15
Normal controller-runtime version: 0.10

Error source code:
code refer: https://book.kubebuilder.io/reference/webhook-for-core-types
```
type PodAnnotator struct {
	Client  client.Client
	decoder *admission.Decoder
}

func (a *PodAnnotator) Handle(ctx context.Context, req admission.Request) admission.Response {
	pod := &corev1.Pod{}
	err := a.decoder.Decode(req, pod)
	if err != nil {
		return admission.Errored(http.StatusBadRequest, err)
	}
        // logic code
	return admission.PatchResponseFromRaw(req.Object.Raw, marshaledPod)
}

func (a *PodAnnotator) InjectDecoder(d *admission.Decoder) error {
	a.decoder = d
	return nil
}
```

Error message:
```
2023/09/21 11:31:25 http: panic serving 10.8.182.142:35552: runtime error: invalid memory address or nil pointer dereference
goroutine 162 [running]:
net/http.(*conn).serve.func1()
        /opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:1854 +0xbf
panic({0x16bf360, 0x269a140})
        /opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/panic.go:890 +0x263
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Decoder).DecodeRaw(0x0, {{0xc0003be400, 0xb23, 0xc00}, {0x0, 0x0}}, {0x1af86e8, 0xc0002c8000})
        /Users/zerunhu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/webhook/admission/decode.go:77 +0x18d
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Decoder).Decode(_, {{{0xc0000e31a0, 0x24}, {{0x0, 0x0}, {0xc000987270, 0x2}, {0xc000987272, 0x3}}, {{0x0, ...}, ...}, ...}}, ...)
        /Users/zerunhu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/webhook/admission/decode.go:49 +0x8e
git.woa.com/KubeGame/kubegame-operator/tcaplus/internal/webhook.(*PodAnnotator).Handle(_, {_, _}, {{{0xc0000e31a0, 0x24}, {{0x0, 0x0}, {0xc000987270, 0x2}, {0xc000987272, ...}}, ...}})
        /Users/zerunhu/kubegame/kubegame-operator/tcaplus/internal/webhook/pod_mutate.go:50 +0x209
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(_, {_, _}, {{{0xc0000e31a0, 0x24}, {{0x0, 0x0}, {0xc000987270, 0x2}, {0xc000987272, ...}}, ...}})
        /Users/zerunhu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/webhook/admission/webhook.go:169 +0x20a
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc0000aa230, {0x7f02eb80ec38?, 0xc000467360}, 0xc00063a100)
        /Users/zerunhu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/webhook/admission/http.go:98 +0xc94
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7f02eb80ec38, 0xc000467360}, 0x1b07f00?)
        /Users/zerunhu/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/promhttp/instrument_server.go:60 +0xd4
net/http.HandlerFunc.ServeHTTP(0x1b07fb0?, {0x7f02eb80ec38?, 0xc000467360?}, 0xc000887828?)
        /opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:2122 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x1b07fb0?, 0xc000170380?}, 0xc00063a100)
        /Users/zerunhu/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/promhttp/instrument_server.go:147 +0xc5
net/http.HandlerFunc.ServeHTTP(0x77fd25?, {0x1b07fb0?, 0xc000170380?}, 0x7f03130935b8?)
        /opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:2122 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x1b07fb0, 0xc000170380}, 0xc00063a100)
        /Users/zerunhu/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/promhttp/instrument_server.go:109 +0xc7
net/http.HandlerFunc.ServeHTTP(0xc000170380?, {0x1b07fb0?, 0xc000170380?}, 0x18a40fb?)
        /opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0000e3181?, {0x1b07fb0, 0xc000170380}, 0xc00063a100)
        /opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0x1afa948?}, {0x1b07fb0, 0xc000170380}, 0xc00063a100)
        /opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc00069a000, {0x1b08bd0, 0xc0000268d0})
        /opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /opt/homebrew/Cellar/go/1.20.3/libexec/src/net/http/server.go:3089 +0x5ed

```

Some clues I found:
The code misalignment is located at: err := a.decoder.Decode(req, pod)
admission.Decoder being nil causes an error in the file /Users/zerunhu/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/webhook/admission/decode.go:77 with the code deserializer := d.codecs.UniversalDeserializer(). It seems that the InjectDecoder function was not executed.
```
func (t *TcaplusCreateUpdateHandler) InjectDecoder(d *admission.Decoder) error {
	t.Decoder = d
	return nil
}
```
It appears that the controller-runtime version 0.15 no longer has this file: webhook/admission/inject.go. Now, if we need to handle core resource Mutating and Validating in the controller, how should we proceed?

**Comment by sbueringer** [comment]
This is not problematic, it was an intended change.

Please see the release notes: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0

> Remove dependency injection functions

**Comment by sbueringer** [comment]
There was a PR in kubebuilder somewhere to update documentation like this (not sure if it's the same part of the docs)

**Comment by sbueringer** [comment]
@zerunhu To give you a concrete example: This is is how we do it: https://github.com/kubernetes-sigs/cluster-api/blob/ea0dc4da091b13bea47dbb6d41340c1f434bac5d/controlplane/kubeadm/internal/webhooks/scale.go#L35

**Comment by troy0820** [comment]
Closing as relevant information was provided for the intended change in the release notes.  

/close
