### ISSUE TITLE
log.SetLogger(...) was never called; logs will not be displayed.

### ISSUE THREAD

**Issue by Noamrok** [kubernetes-sigs/controller-runtime#2622]
Hi,

Since upgrading to controller runtime 0.16.3 we are having this issue when creating a new controller runtime client.
It's not a blocker to our pipeline, just another log

_how to reproduce_:

```
import "sigs.k8s.io/controller-runtime/pkg/client"
client, err := client.New(config, client.Options{})
```

_full stacktrace_:

```
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
        >  goroutine 1 [running]:
        >  runtime/debug.Stack()
        >       /usr/local/go/src/runtime/debug/stack.go:24 +0x6b
        >  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
        >       /home/noam/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/log.go:60 +0xa5
        >  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc000683a00, {0x928297f, 0x14})
        >       /home/noam/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/deleg.go:147 +0x45
        >  github.com/go-logr/logr.Logger.WithName({{0x99b3660, 0xc000683a00}, 0x0}, {0x928297f, 0x14})
        >       /home/noam/go/pkg/mod/github.com/go-logr/logr@v1.2.0/logr.go:293 +0x56
        >  sigs.k8s.io/controller-runtime/pkg/client.newClient(0xc000d55b00, {0x0, 0x0, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0})
        >       /home/noam/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/client/client.go:122 +0x139
        >  sigs.k8s.io/controller-runtime/pkg/client.New(0xc000d54b40, {0x0, 0x0, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0})
        >       /home/noam/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/client/client.go:103 +0xcc
```

**Comment by sbueringer** [comment]
Sounds like you have to call `log.SetLogger(...)` and if you don't logs from controller-runtime will not be displayed

**Comment by Noamrok** [comment]
apparently it was in the breaking change release notes of 0.15.0, I will close this issue, thank you!
