### ISSUE TITLE
Data race with various client APIs

### ISSUE THREAD

**Issue by tdiesler** [kubernetes-sigs/controller-runtime#2782]
We see various data race conditions in [Camel-K](https://github.com/apache/camel-k) and I'm starting to wonder whether this is really on our side. Perhaps you could comment on how these APIs are supposed to get used

```
package client
Client.List(ctx context.Context, obj ObjectList, opts ...ListOption) error
```

```
  fatal error: concurrent map read and map write
  
  goroutine 15404 [running]:
  k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc0002ae540, {0x2e5ddb0?, 0xc0004a2930})
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/runtime/scheme.go:267 +0x1ad
  k8s.io/apimachinery/pkg/runtime/serializer/protobuf.(*Serializer).Decode(0xc0008d5140, {0xc00140a000?, 0x1010f?, 0x12000?}, 0x0, {0x2e5ddb0?, 0xc0004a2930?})
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/runtime/serializer/protobuf/protobuf.go:132 +0x458
  k8s.io/apimachinery/pkg/runtime.WithoutVersionDecoder.Decode({{0x7f39dc397fd8?, 0xc0008d5140?}}, {0xc00140a000?, 0x199?, 0xc0004a2930?}, 0x259db80?, {0x2e5ddb0?, 0xc0004a2930?})
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.28.8/pkg/runtime/helper.go:252 +0x4f
  sigs.k8s.io/controller-runtime/pkg/client/apiutil.targetZeroingDecoder.Decode({{0x2e54ea0?, 0xc00107c050?}}, {0xc00140a000, 0x1010f, 0x12000}, 0x0?, {0x2e5ddb0?, 0xc0004a2930?})
  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.5/pkg/client/apiutil/apimachinery.go:236 +0xb0
  k8s.io/client-go/rest.Result.Into({{0xc00140a000, 0x1010f, 0x12000}, {0x0, 0x0, 0x0}, {0xc000144060, 0x23}, {0x0, 0x0}, ...}, ...)
  	/home/runner/go/pkg/mod/k8s.io/client-go@v0.28.8/rest/request.go:1373 +0x97
  sigs.k8s.io/controller-runtime/pkg/client.(*typedClient).List(0xc0008e8900, {0x2e7a818, 0x44b0940}, {0x2e87cc0?, 0xc0004a2930}, {0xc0009ba9c0, 0x2, 0x3655?})
  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.5/pkg/client/typed_client.go:165 +0x2a5
  sigs.k8s.io/controller-runtime/pkg/client.(*client).List(0xc0008e8900, {0x2e7a818, 0x44b0940}, {0x2e87cc0?, 0xc0004a2930?}, {0xc0009ba9c0, 0x2, 0x2})
  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.5/pkg/client/client.go:402 +0x3e5
```

In [package runtime](https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime@v0.28.8#SchemeBuilder.AddToScheme) (i.e. not this project)

```
package runtime
SchemeBuilder.AddToScheme(s *Scheme) error
```

```
  fatal error: concurrent map read and map write
  
  goroutine 627 [running]:
  k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName(0xc0004df420, {{0x0, 0x0}, {0x271d9c7, 0x2}, {0x20d77d9, 0xb}}, {0x2d8c730?, 0xc000e180a0})
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.7/pkg/runtime/scheme.go:170 +0x1d7
  k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes(0xc0004df420, {{0x0?, 0x46f9d3?}, {0x271d9c7?, 0xc000775460?}}, {0xc0007755f0?, 0x5, 0xc00086e4b0?})
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.7/pkg/runtime/scheme.go:148 +0x176
  k8s.io/apimachinery/pkg/runtime.(*Scheme).AddUnversionedTypes(0xc0004df420, {{0x0?, 0x13?}, {0x271d9c7?, 0xa?}}, {0xc0007755f0?, 0x5, 0x5?})
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.7/pkg/runtime/scheme.go:124 +0xaf
  k8s.io/apimachinery/pkg/apis/meta/v1.AddToGroupVersion(0xc0004df420?, {{0x273b4c9?, 0x272323e?}, {0x271d9c7?, 0x27283c9?}})
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.7/pkg/apis/meta/v1/register.go:75 +0x335
  knative.dev/serving/pkg/apis/serving/v1.addKnownTypes(0x2db0600?)
  	/home/runner/go/pkg/mod/knative.dev/serving@v0.39.3/pkg/apis/serving/v1/register.go:59 +0x20b
  k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(...)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.7/pkg/runtime/scheme_builder.go:29
  k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(...)
  	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.7/pkg/runtime/scheme_builder.go:29
```

**Comment by sbueringer** [comment]
Are you adding types to the scheme after initial startup?

**Comment by alvaroaleman** [comment]
This is `runtime.Scheme` not being threadsafe and unrelated to controller-runtime

**Comment by alvaroaleman** [comment]
Closing this, as this is in a package that is not part of controller-runtime. Please open an issue in the main kubernetes/kubernetes repo if you want to see this improved.
