### ISSUE TITLE
flag redefined: kubeconfig: allow double vendoring this library but still register flags on behalf of users

### ISSUE THREAD

**Issue by akoserwal** [kubernetes-sigs/controller-runtime#878]
Error:
```
 /var/folders/3d/_kgky9bj61g5144z004y51qr0000gp/T/go-build652443801/b001/e2e.test flag redefined: kubeconfig
panic: /var/folders/3d/_kgky9bj61g5144z004y51qr0000gp/T/go-build652443801/b001/e2e.test flag redefined: kubeconfig

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000d2120, 0x244c6a0, 0xc00004e250, 0x224908b, 0xa, 0x225fced, 0x12)
    /usr/local/Cellar/go/1.13.8/libexec/src/flag/flag.go:848 +0x4ae
flag.(*FlagSet).StringVar(...)
    /usr/local/Cellar/go/1.13.8/libexec/src/flag/flag.go:751
github.com/operator-framework/operator-sdk/pkg/test.(*frameworkOpts).addToFlagSet(0xc00004e240, 0xc0000d2120)
    /Users/akoserwa/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.15.1/pkg/test/framework.go:102 +0x1bf
github.com/operator-framework/operator-sdk/pkg/test.MainEntry(0xc00040d280)
    /Users/akoserwa/go/pkg/mod/github.com/operator-framework/operator-sdk@v0.15.1/pkg/test/main_entry.go:27 +0x50
github.com/atlasmap/atlasmap-operator/test/e2e.TestMain(...)
       _testmain.go:42 +0x136
```
Using :- 
```
framework “github.com/operator-framework/operator-sdk/pkg/test” where it is setting
> flagset.StringVar(&opts.kubeconfigPath, KubeConfigFlag, “”, “path to kubeconfig”)
```

And in my test case, I am using a library which is also using controller-runtime/operator-sdk
```github.com/RHsyseng/operator-utils/pkg/utils/openshift```

 Method I am calling: `openshift.IsOpenShift(framework.KubeConfig)`

controller-runtime/pkg/client/config/config.go
```
// TODO: Fix this to allow double vendoring this library but still register flags on behalf of users
  flag.StringVar(&kubeconfig, “kubeconfig”, “”,
    “Paths to a kubeconfig. Only required if out-of-cluster.“)
```
 I suspect fixing TODO will resolve it? If yes, I would like to work on it.

**Comment by DirectXMan12** [comment]
So, due to some legacy cruft, controller-runtime expects to be the thing that registers that flag.  We probably shouldn't but that's a pretty serious breaking change that I don't think we want to make just yet.

cc @shawn-hurley @camilamacedo86 @joelanford @estroz any of you have insight into what the operatorsdk package is doing that it's re-registering that flag?

**Comment by DirectXMan12** [comment]
/assign @camilamacedo86 

to answer or triage elsewhere.

**Comment by estroz** [comment]
The SDK's test framework uses some client-go APIs directly and requires the kubeconfig's namespace, so it needs the kubeconfig path. While the framework could/should be refactored to use pure controller-runtime, which would allow the framework to delegate registering this flag to controller-runtime, we can use a local flagset in the mean time.

PR: https://github.com/operator-framework/operator-sdk/pull/2731

**Comment by akoserwal** [comment]
Getting error:
```
flag provided but not defined: -singleNamespace
Usage of /var/folders/3d/_kgky9bj61g5144z004y51qr0000gp/T/go-build683683410/b001/e2e.test:
  -globalMan string
        path to operator manifest
  -kubeconfig string
        Paths to a kubeconfig. Only required if out-of-cluster.
  -localOperator
        enable if operator is running locally (not in cluster)
  -localOperatorArgs string
        flags that the operator needs (while using --up-local). example: "--flag1 value1 --flag2=value2"
  -master --kubeconfig
```
private variable:
singleNamespaceMode bool

**Comment by camilamacedo86** [comment]
Hi @estroz,

Since you are working on it already.  /assign @estroz

**Comment by estroz** [comment]
@akoserwal try out SDK's master.

**Comment by lrascao** [comment]
For future reference, this is lookup workaround mentioned by @estroz :

`	kubeconfig := flag.Lookup("kubeconfig").Value.String()`

**Comment by mvleandro** [comment]
> For future reference, this is the lookup workaround mentioned by @estroz :
> 
> ` kubeconfig := flag.Lookup("kubeconfig").Value.String()`

Thank you!

**Comment by stevekuznetsov** [comment]
/reopen

It's been a bit. This is still super annoying for basically anyone who happens to import any part of `controller-runtime`. Mutating global state in an `init()` in a library is fairly unpleasant - made worse by the fact that Go will only complain the _second_ time the flag is registered, and because of `init()` ordering, `controller-runtime` is always the first one, so finding what just side-effect registered `--kubeconfig` is impossible.

I'd really suggest another look at this. If this were defined in some runtime code or in code that's unlikely to be imported unless by someone actually using `controller-runtime`, perhaps it would be less frustrating. In my case, I imported an API module that happened to use the `controller-runtime` Scheme builder. Really divorced from any runtime considerations.

A workaround for now is to re-set `flag.CommandLine` in my own `init()`.

cc @joelanford  @vincepri @alvaroaleman
